# Generated by Django 5.0.6 on 2024-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_rename_anioproyecto_proyectos_fechaproyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='descripcionproyecto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='fechaproyecto',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='proyectoimg',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='nombreproyecto',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
